### ISSUE TITLE
ModuleNotFoundError: No module named 'UserDict'

### ISSUE THREAD

**Issue by jaskiratr** [ecometrica/gdal2mbtiles#15]
Hi,
I'm trying to run gdal2mbtiles in Ubuntu 16.04.1 LTS terminal (Linux bash shell in Win10) and python 2.7 virtual environment created through Anaconda.

After installation of dependencies and establishing symlink for vipscc, `gdal2mbtiles --help` runs successfully. However when I try to convert the GeoTiff to MbTiles, I receive the following error about UserDict missing.

This is something that I'm not able to install via pip either. Is there any way to resolve this?

Thank you!

```
Traceback (most recent call last):
  File "C:\Users\Jess\Anaconda3\Scripts\gdal2mbtiles-script.py", line 11, in <module>
    load_entry_point('gdal2mbtiles==1.3.2', 'console_scripts', 'gdal2mbtiles')()
  File "C:\Users\Jess\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Jess\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "C:\Users\Jess\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "C:\Users\Jess\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Jess\Anaconda3\lib\site-packages\gdal2mbtiles\main.py", line 52, in <module>
    from .mbtiles import Metadata
  File "C:\Users\Jess\Anaconda3\lib\site-packages\gdal2mbtiles\mbtiles.py", line 28, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
```

**Comment by jaskiratr** [comment]
Ah, looks like it was a Conda environment issue. 
Closing this.
