### ISSUE TITLE
Error "default_rgba.png" not found

### ISSUE THREAD

**Issue by alanlun516** [ecometrica/gdal2mbtiles#20]
I guess "default_rgba.png" missing.

When executing
```
$ gdal2mbtiles --spatial-reference 4326 test.tiff test.mbtiles
```
it shows an error
```
File ".../gdal2mbtiles/storages.py", line 86, in _border_image
    width, height, ink=rgba(r=0, g=0, b=0, a=0)
  File ".../gdal2mbtiles/vips.py", line 166, in new_rgba
    os.path.dirname(os.path.realpath(__file__)), 'default_rgba.png'
  File ".../pyvips/vimage.py", line 210, in new_from_file
    raise Error('unable to load from file {0}'.format(vips_filename))
pyvips.error.Error: unable to load from file .../gdal2mbtiles/default_rgba.png
  VipsForeignLoad: file ".../gdal2mbtiles/default_rgba.png" not found
```

**Comment by swen100** [comment]
Still getting this error also with the latest version:
```
Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 33, in <module>
    sys.exit(load_entry_point('gdal2mbtiles==2.1.5', 'console_scripts', 'gdal2mbtiles')())
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/main.py", line 297, in main
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/helpers.py", line 203, in warp_mbtiles
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/helpers.py", line 75, in image_mbtiles
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/vips.py", line 1068, in slice
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/vips.py", line 995, in slice_downsample
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/vips.py", line 759, in fill_borders
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/storages.py", line 295, in save_border
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/storages.py", line 85, in _border_image
  File "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/vips.py", line 164, in new_rgba
  File "/usr/local/lib/python3.9/dist-packages/pyvips-2.2.1-py3.9-linux-x86_64.egg/pyvips/vimage.py", line 349, in new_from_file
    raise Error('unable to load from file {0}'.format(vips_filename))
pyvips.error.Error: unable to load from file b'/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/default_rgba.png'
  VipsForeignLoad: file "/usr/local/lib/python3.9/dist-packages/gdal2mbtiles-2.1.5-py3.9.egg/gdal2mbtiles/default_rgba.png" does not exist
```

**Comment by solsticedhiver** [comment]
I have installed from pip and I still have that error. No idea why?

It's the same with installing from git and `./setup.py install --user`

**Comment by solsticedhiver** [comment]
The previous commit says "it should fix it..." but have you tried/tested it?

Here is my fix:

```diff
diff --git a/gdal2mbtiles/vips.py b/gdal2mbtiles/vips.py
index 1327a42..54c56a6 100644
--- a/gdal2mbtiles/vips.py
+++ b/gdal2mbtiles/vips.py
@@ -30,6 +30,7 @@ import logging
 from math import ceil, floor
 from multiprocessing import cpu_count
 from operator import itemgetter
+import pkgutil
 
 import numexpr
 import numpy
@@ -161,11 +162,7 @@ class VImageAdapter(object):
         # which is a few byes different when written back to memory, which means
         # we can't store and retrieve it from its hash.  So instead we use a
         # temporary transparent 256x256 file for the initial image
-        image = Image.new_from_file(
-            os.path.join(
-                os.path.dirname(os.path.realpath(__file__)), 'default_rgba.png'
-            )
-        )
+        image = Image.new_from_buffer(pkgutil.get_data(__name__, 'default_rgba.png'), '')
         image = image.copy(
             width=width, height=height,
             coding='none',  # No coding and no compression

```

Actually, this works now
