### ISSUE TITLE
Throws error: pyvips.error.Error: unable to call embed   linear: vector must have 1 or 3 elements

### ISSUE THREAD

**Issue by caleb87** [ecometrica/gdal2mbtiles#26]
Script runs for awhile, then throws the following error. 

Running Ubuntu 18.04, gdalinfo is 2.2.3. Any ideas?

```
ubuntu@:~$ sudo gdal2mbtiles --min-resolution 1 --max-resolution 15 test.tif test.mbtiles
Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.1', 'console_scripts', 'gdal2mbtiles')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/main.py", line 309, in main
    colors=colors, band=band)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/helpers.py", line 211, in warp_mbtiles
    pngdata=pngdata)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/helpers.py", line 75, in image_mbtiles
    pyramid.slice(fill_borders=fill_borders)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/vips.py", line 1081, in slice
    fill_borders=fill_borders)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/vips.py", line 990, in slice_downsample
    levels=(self.resolution - max_resolution),
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/vips.py", line 835, in downsample
    offset=offset)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gdal2mbtiles/vips.py", line 428, in tms_align
    x, y, width, height, background=[0, 0, 0, 0]  # Transparent
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyvips/vimage.py", line 804, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pyvips/voperation.py", line 189, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call embed linear: vector must have 1 or 3 elements
```

**Comment by jordiecometrica** [comment]
Can you provide the test tif that generated this error?

**Comment by caleb87** [comment]
The files are available here:

http://54.161.226.75/original.tif
http://54.161.226.75/epsg3857.tif

original.tif (about 15MB) is the image I started with, and epsg3857 which has been converted to EPSG 3857 (about 150MB). Both are throwing the error.

**Comment by jordiecometrica** [comment]
No guarantee that anyone will look at this any time soon. Can you keep that AWS server serving that file indefinitely?

**Comment by jordiecometrica** [comment]
[original.tif.txt](https://github.com/ecometrica/gdal2mbtiles/files/3019865/original.tif.txt)

Okay, figured it out. Had to change the filename extension so that github would allow it.

**Comment by ten2net** [comment]
I also have this problem. My environment: python3.X + gdal3.X

**Comment by karfam** [comment]
Same problem here with a 30000 pixel tif.
At first I thought it was a problem of gdal 3 that get installed with the instructions, but the problem continues even with installing gdal 2.4.4

**Comment by csustjl** [comment]
Now I have this problem too, did you solve this problem before?  gdal=2.2.2  pyvips=2.1.8  GDal2mbtiles = 2.1.0

**Comment by richwrd** [comment]
I have the same problem, has anyone found a solution?
