### ISSUE TITLE
Unsupported SRS

### ISSUE THREAD

**Issue by ghemann** [ecometrica/gdal2mbtiles#28]
I'm getting issues about identifying the right SRS.  Whether I let the system detect it or set it manually using --spatial-reference, I get the same error.
I've pasted the error, as well as the output from gdalinfo of my tif.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/gdal.py", line 457, in GetSpatialReference
  File "/home/ubuntu/.local/lib/python3.6/site-packages/osgeo/osr.py", line 808, in AutoIdentifyEPSG
    return _osr.SpatialReference_AutoIdentifyEPSG(self, *args)
RuntimeError: OGR Error: Unsupported SRS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.1', 'console_scripts', 'gdal2mbtiles')()
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/main.py", line 309, in main
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/helpers.py", line 194, in warp_mbtiles
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/gdal.py", line 497, in GetNativeResolution
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/gdal.py", line 463, in GetSpatialReference
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles-2.1.1-py3.6.egg/gdal2mbtiles/gdal.py", line 799, in FromEPSG
  File "/home/ubuntu/.local/lib/python3.6/site-packages/osgeo/osr.py", line 1138, in ImportFromEPSG
    return _osr.SpatialReference_ImportFromEPSG(self, *args)
TypeError: in method 'SpatialReference_ImportFromEPSG', argument 2 of type 'int'
```

gdalinfo output

```
Driver: GTiff/GeoTIFF
Files: mmr.tif
Size is 13797, 16140
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.2572221010042,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",42.83333333333334],
    PARAMETER["central_meridian",-70.16666666666667],
    PARAMETER["scale_factor",0.9999666666666667],
    PARAMETER["false_easting",2952750],
    PARAMETER["false_northing",0],
    UNIT["US survey foot",0.3048006096012192,
        AUTHORITY["EPSG","9003"]]]
Origin = (2908649.651220000348985,295540.606010000046808)
Pixel Size = (0.059410639269400,-0.059410452912021)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( 2908649.651,  295540.606) ( 70d19'59.77"W, 43d38'38.64"N)
Lower Left  ( 2908649.651,  294581.721) ( 70d19'59.75"W, 43d38'29.17"N)
Upper Right ( 2909469.340,  295540.606) ( 70d19'48.62"W, 43d38'38.66"N)
Lower Right ( 2909469.340,  294581.721) ( 70d19'48.60"W, 43d38'29.19"N)
Center      ( 2909059.496,  295061.164) ( 70d19'54.19"W, 43d38'33.92"N)
Band 1 Block=13797x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=13797x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=13797x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=13797x1 Type=Byte, ColorInterp=Alpha

```

**Comment by tomowatt** [comment]
Could you check if the TIF you are using opens correctly in QGIS for instance to check the projection? As from the GDAL Info you posted, I can see that `PROJCS["unnamed"` which may be the source of the issue

**Comment by ghemann** [comment]
thanks @tomowatt 
It loads fine in QGIS, and this is the information in properties

```
CRS | USER:100005 - * Generated CRS (+proj=tmerc +lat_0=42.83333333333334 +lon_0=-70.16666666666667 +k=0.9999666666666667 +x_0=900000 +y_0=0 +datum=NAD83 +units=us-ft +no_defs) - Projected
-- | --
Extent | 2908752.3810246167704463,294692.1781486307736486 : 2909369.3012850000523031,295431.4834046270116232
```
100005 is a custom CRS but when i manually load this information from a small python script, it seems to work fine

```
import gdal, osr
tif = gdal.Open(file.tif)
proj = osr.SpatialReference(wkt=tif.GetProjection())
```

**Comment by ghemann** [comment]
In addition, if I supply --spatial-reference, shouldn't it ignore this custom one in the tif?

**Comment by tomowatt** [comment]
```
    def GetEPSGCode(self):
        epsg_string = self.GetEPSGString()
        if epsg_string:
            return int(epsg_string.split(':')[1])
        else:
            # HACK: The following is to cope with the fact that the Wkt
            #       representation of the Web Mercator is different for
            #       ESRI's WKID 102100 and EPSG's 3857 while both are
            #       equivalent. Yet, Proj4 does not understand ESRI's
            #       'mercator_auxiliary_sphere' projection name.
            projcs_name = self.GetAttrValue(str('PROJCS'))
            # Returning equivalent EPSG code
            if projcs_name == ESRI_102100_PROJ:
                return 3857
            elif projcs_name == ESRI_102113_PROJ:
                return 3785
```

So there is a bug with the Spatial Reference not being overwritten via the parameters or returning a correct Projection due to hardcoded logic which results in the issue you are experiencing, we'll see if it can be corrected when possible
