### ISSUE TITLE
gdalwarp - No target filename specified

### ISSUE THREAD

**Issue by cdpwest** [ecometrica/gdal2mbtiles#3]
When I run gdal2mbtiles I get the following error:

gdal2mbtiles ./Untitled.tif 
Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 9, in <module>
    load_entry_point('gdal2mbtiles==1.3.0', 'console_scripts', 'gdal2mbtiles')()
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/main.py", line 283, in main
    colors=colors, band=band)
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/helpers.py", line 189, in warp_mbtiles
    resampling=resampling, compress='LZW')
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/gdal.py", line 111, in preprocess
    functions=functions, compress=compress, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/gdal.py", line 129, in pipeline
    vrt = f(previous)
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/gdal.py", line 206, in warp
    return VRT(check_output_gdal([str(e) for e in warp_cmd]))
  File "/usr/local/lib/python2.7/dist-packages/gdal2mbtiles/gdal.py", line 73, in check_output_gdal
    error=stderrdata.rstrip('\n'))
gdal2mbtiles.exceptions.CalledGdalError: Command '['gdalwarp', '-q', '-of', 'VRT', '-t_srs', 'EPSG:3857', '-r', 'near', './Untitled.tif', '/dev/stdout']' returned non-zero exit status 1: 
FAILURE: No target filename specified.

But running gdalwarp on its own with the above args it appears to work.

**Comment by mghughes** [comment]
Just getting around to this, sorry for the delay.

I can't seem to reproduce this. Could you paste the output of `gdalinfo` for your input file? And any other information you can provide, like environment and gdal version?
