### ISSUE TITLE
TypeError: in method 'SpatialReference_ImportFromEPSG', argument 2 of type 'int'

### ISSUE THREAD

**Issue by ryanjkelly** [ecometrica/gdal2mbtiles#30]
I'm trying to convert the TIFFs from the FAA's [VFR Raster Charts](https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/vfr/) page and I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.1', 'console_scripts', 'gdal2mbtiles')()
  File "/home/ryan/.local/lib/python2.7/site-packages/gdal2mbtiles/main.py", line 309, in main
    colors=colors, band=band)
  File "/home/ryan/.local/lib/python2.7/site-packages/gdal2mbtiles/helpers.py", line 194, in warp_mbtiles
    validate_resolutions(resolution=dataset.GetNativeResolution(),
  File "/home/ryan/.local/lib/python2.7/site-packages/gdal2mbtiles/gdal.py", line 497, in GetNativeResolution
    dst_ref = self.GetSpatialReference()
  File "/home/ryan/.local/lib/python2.7/site-packages/gdal2mbtiles/gdal.py", line 463, in GetSpatialReference
    sr = sr.FromEPSG(sr.GetEPSGCode())
  File "/home/ryan/.local/lib/python2.7/site-packages/gdal2mbtiles/gdal.py", line 799, in FromEPSG
    s.ImportFromEPSG(code)
  File "/home/ryan/.local/lib/python2.7/site-packages/osgeo/osr.py", line 1138, in ImportFromEPSG
    return _osr.SpatialReference_ImportFromEPSG(self, *args)
TypeError: in method 'SpatialReference_ImportFromEPSG', argument 2 of type 'int'
```

Here is the output from `gdalinfo -noct test.tif`:

```
Driver: GTiff/GeoTIFF
Files: test.tif
Size is 17921, 12358
Coordinate System is:
PROJCS["Lambert Conformal Conic",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.2572221010042,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",46.66666666666666],
    PARAMETER["standard_parallel_2",41.33333333333334],
    PARAMETER["latitude_of_origin",42.3],
    PARAMETER["central_meridian",-97],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (-411171.578339697443880,257040.430107307882281)
Pixel Size = (42.335440573740584,-42.334973725198978)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2019:06:21 12:39:53
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=Adobe Photoshop CS5.1 Windows
  TIFFTAG_XRESOLUTION=300
  TIFFTAG_YRESOLUTION=300
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -411171.578,  257040.430) (102d10'43.70"W, 44d29'57.95"N)
Lower Left  ( -411171.578, -266135.175) (101d47'45.50"W, 39d47'47.93"N)
Upper Right (  347521.852,  257040.430) ( 92d37'16.44"W, 44d31'57.52"N)
Lower Right (  347521.852, -266135.175) ( 92d56'42.51"W, 39d49'38.48"N)
Center      (  -31824.863,   -4547.373) ( 97d23' 9.33"W, 42d15'30.11"N)
Band 1 Block=17921x1 Type=Byte, ColorInterp=Palette
  Color Table (RGB with 256 entries)
```

I'm using:

```
Ubuntu 18.04
Python 2.7.15+
pip 9.0.1
gdal2mbtiles 2.1.1
GDAL 2.4.2
```

**Comment by darrenleeweber** [comment]
@rebkwok - is any maintainer able to fix this soon?  Is there any WIP/PR to address it?

**Comment by damon-rand** [comment]
@darrenleeweber Not sure when we will get to addressing this particular issue. PRs accepted.

**Comment by darrenleeweber** [comment]
@damon-rand - I'm not likely to work on this until it's essential to upgrade to a new version of GDAL and even then I'm not likely to work on it, as I have no experience with developing this project.  If the contributors who develop this project have abandoned it, that would be good to know.

**Comment by damon-rand** [comment]
@darrenleeweber Nothing has been abandoned. We welcome and merge community contributions and our own. We just have other, more pressing, priorities than this one.

**Comment by jordiecometrica** [comment]
I don't think we want to declare abandonment yet, since we will gladly merge PRs. This particular issue, however, does not directly affect us, so we have little motivation to fix it ourselves.

If on the other hand you think you could do a better job of coordinating development or you know someone who can, by all means, fork and improve. We certainly won't feel slighted if you do.

**Comment by darrenleeweber** [comment]
I suggest this issue is marked as a bug when using GDAL 3.x and the priority to fix bugs should be high enough for core project developers to attend to it.

**Comment by tomowatt** [comment]
```
    def GetEPSGCode(self):
        epsg_string = self.GetEPSGString()
        if epsg_string:
            return int(epsg_string.split(':')[1])
        else:
            # HACK: The following is to cope with the fact that the Wkt
            #       representation of the Web Mercator is different for
            #       ESRI's WKID 102100 and EPSG's 3857 while both are
            #       equivalent. Yet, Proj4 does not understand ESRI's
            #       'mercator_auxiliary_sphere' projection name.
            projcs_name = self.GetAttrValue(str('PROJCS'))
            # Returning equivalent EPSG code
            if projcs_name == ESRI_102100_PROJ:
                return 3857
            elif projcs_name == ESRI_102113_PROJ:
                return 3785
```

So there is a bug with the Spatial Reference not being overwritten via the parameters or returning a correct Projection due to hardcoded logic which results in the issue @ryanjkelly is experiencing, we'll see if it can be corrected when possible

**Comment by elfmanryan** [comment]
Neen looking at this today aswell. going back bit earlier, when a Dataset is instantiated (helpers.py, line 193),  attempts at calling the method GetSpatialReference() raises an error if the epsg is not recognised by method sr.AutoIdentifyEPSG() (gdal.py, line 458). This is true for the lambert canonical projection on the .tif above. 
However we catch that error (gdal.py, line 460), and then try to instantiate another SpatialReference obj from epsg 3857 (a.k.a pseudo webmercator) (line 463) - here in lies the final error :  'argument type 2 is int' created by the method FromEPSG() (gdal.py line 798)   
This method is inherited and same as calling osr.SpatialReference.FromEPSG(3857) which works. so the problem seems to be the way its inherited in our wrapper. (see below)
apologies if that was convoluted. written at end of the day in a hurry. 

`class SpatialReference(osr.SpatialReference):
    def __init__(self, *args, **kwargs):
        super(SpatialReference, self).__init__(*args, **kwargs)
        self._angular_transform = None

    @classmethod
    def FromEPSG(cls, code):
        s = cls()
        s.ImportFromEPSG(code) #<--------int error here
        return s`

**Comment by dazza-codes** [comment]
Our team has bumped into this bug again, so now it's a blocker and I have to focus on a solution, either tracking down the bug with a quick hack-fix or finding a set of versions that work or looking closer at the CRS in our GeoTIFFs.

First, simple question - master has a few commits since the `2.1.1` release that target some CRS unit tests and possible fixes, so I'll try master and ask whether or not this might be fixed and released in a new patch release?
