### ISSUE TITLE
TypeError LoadLibrary() argument 1 must be str, not None

### ISSUE THREAD

**Issue by prasanjitdash** [ecometrica/gdal2mbtiles#38]
Python 3.7.6
GDAL 3.0.4, released 2020/01/28
Windows 10, 64 bit

gdal works normally as expected, e.g., `gdal_translate`

`gdal2mbtiles -h` shows help items.

Installed gdal2mbtiles with git; installation has no error message.

While running on a test tif image, the following error is thrown. It seems related to LoadLibrary() and being new to this new stack (python, gdal, gdal2mbtiles), I'm confused where the error is coming from and where to look. Is it related or unrelated to gdal2mbtiles. Python seems to be working normally.

`gdal2mbtiles test_cl.tif test.mbt --name TEST --description CMCSST --layer-type overlay --version 0.0 --format png --spatial-reference 4326 --resampling near --min-resolution 2 --max-resolution 7 --fill-borders --png8 256 --coloring palette --color="0:#ff00ff"
`

**Error**
Traceback (most recent call last):
  File "C:\Users\Dash\Anaconda3\Scripts\gdal2mbtiles-script.py", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.2', 'console_scripts', 'gdal2mbtiles')()
  File "C:\Users\Dash\Anaconda3\lib\site-packages\gdal2mbtiles-2.1.2-py3.7.egg\gdal2mbtiles\main.py", line 264, in main
  File "C:\Users\Dash\Anaconda3\lib\site-packages\gdal2mbtiles-2.1.2-py3.7.egg\gdal2mbtiles\main.py", line 231, in parse_args
  File "C:\Users\Dash\Anaconda3\lib\site-packages\gdal2mbtiles-2.1.2-py3.7.egg\gdal2mbtiles\main.py", line 65, in coloring_arg
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\Dash\Anaconda3\lib\site-packages\gdal2mbtiles-2.1.2-py3.7.egg\gdal2mbtiles\vips.py", line 116, in <module>
  File "C:\Users\Dash\Anaconda3\lib\site-packages\gdal2mbtiles-2.1.2-py3.7.egg\gdal2mbtiles\vips.py", line 87, in __init__
  File "C:\Users\Dash\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Dash\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
**TypeError: LoadLibrary() argument 1 must be str, not None**

Can someone put me on the right track where to look for the issue or help me to troubleshoot?
Thank you

**Comment by elfmanryan** [comment]
Hi sorry for the delayed reply, i notice building loading this via anaconda distribution; have you tried via pip? looks like a compatibility issue
