### ISSUE TITLE
if '/' in name or '\\' in name: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by keepbeer** [ecometrica/gdal2mbtiles#53]
anyone here solve the problem?
D:\mbtitles\gdal2mbtiles>gdal2mbtiles D:\img\test\guangdong_test\guangzhou_ys_05.tif D:\img\tiles\guangzhou.mbtiles --min-resolution 4 --max-resolution 12
Traceback (most recent call last):
  File "D:\Program Files\Python311\Scripts\gdal2mbtiles-script.py", line 33, in <module>
    sys.exit(load_entry_point('gdal2mbtiles==2.1.5', 'console_scripts', 'gdal2mbtiles')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gdal2mbtiles-2.1.5-py3.11.egg\gdal2mbtiles\main.py", line 264, in main
  File "D:\Program Files\Python311\Lib\site-packages\gdal2mbtiles-2.1.5-py3.11.egg\gdal2mbtiles\main.py", line 231, in parse_args
  File "D:\Program Files\Python311\Lib\site-packages\gdal2mbtiles-2.1.5-py3.11.egg\gdal2mbtiles\main.py", line 65, in coloring_arg
  File "D:\Program Files\Python311\Lib\site-packages\gdal2mbtiles-2.1.5-py3.11.egg\gdal2mbtiles\vips.py", line 116, in <module>
  File "D:\Program Files\Python311\Lib\site-packages\gdal2mbtiles-2.1.5-py3.11.egg\gdal2mbtiles\vips.py", line 87, in __init__
  File "D:\Program Files\Python311\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by keepbeer** [comment]
it run in windown x64
